// Package admin provides the teacher/admin review surface for OmniScore:
// a passphrase-gated cookie, a per-question approval workflow, and an
// inline editor that writes back to the on-disk test.json (the canonical
// source of truth) and hot-reloads the running server.
package admin

import (
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/json"
	"errors"
	"net/http"
	"os"
	"strings"
	"time"
)

const (
	adminCookieName = "omniscore_admin"
	adminCookieTTL  = 60 * 60 * 24 // 24h — admins should re-auth daily
)

// Auth manages the passphrase + signed cookie pair for the admin surface.
// The passphrase lives next to the existing omniscore.key file; it is
// generated on first boot and printed once in the startup banner.
type Auth struct {
	key        []byte
	passphrase string
}

// NewAuth loads or creates the admin-key file. The returned passphrase is
// what the operator types into the login form. Generated bytes are 24
// base32-ish characters; readable enough to type by hand.
func NewAuth(keyPath string) (*Auth, string, error) {
	if raw, err := os.ReadFile(keyPath); err == nil {
		pass := strings.TrimSpace(string(raw))
		if pass != "" {
			return &Auth{key: deriveKey(pass), passphrase: pass}, pass, nil
		}
	}
	pass, err := generatePassphrase()
	if err != nil {
		return nil, "", err
	}
	if err := os.WriteFile(keyPath, []byte(pass+"\n"), 0o600); err != nil {
		return nil, "", err
	}
	return &Auth{key: deriveKey(pass), passphrase: pass}, pass, nil
}

func deriveKey(pass string) []byte {
	sum := sha256.Sum256([]byte(pass))
	return sum[:]
}

func generatePassphrase() (string, error) {
	var b [16]byte
	if _, err := rand.Read(b[:]); err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(b[:]), nil
}

// LoginRequest is the body of POST /api/admin/login.
type LoginRequest struct {
	Passphrase string `json:"passphrase"`
}

// Login verifies the submitted passphrase and sets the admin cookie.
func (a *Auth) Login(w http.ResponseWriter, r *http.Request) {
	var req LoginRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, "bad json")
		return
	}
	if subtleEq(req.Passphrase, a.passphrase) != nil {
		writeError(w, http.StatusUnauthorized, "invalid passphrase")
		return
	}
	http.SetCookie(w, &http.Cookie{
		Name:     adminCookieName,
		Value:    a.signClaims(claims{Role: "admin", IssuedAt: time.Now().Unix()}),
		Path:     "/",
		HttpOnly: true,
		SameSite: http.SameSiteLaxMode,
		MaxAge:   adminCookieTTL,
	})
	writeJSON(w, http.StatusOK, map[string]string{"role": "admin"})
}

// Logout clears the cookie.
func (a *Auth) Logout(w http.ResponseWriter, _ *http.Request) {
	http.SetCookie(w, &http.Cookie{Name: adminCookieName, Value: "", Path: "/", MaxAge: -1})
	w.WriteHeader(http.StatusNoContent)
}

// Whoami returns 200 + the cookie's role if it verifies, else 401.
func (a *Auth) Whoami(w http.ResponseWriter, r *http.Request) {
	c, err := a.verify(r)
	if err != nil {
		writeError(w, http.StatusUnauthorized, "not signed in")
		return
	}
	writeJSON(w, http.StatusOK, map[string]string{"role": c.Role})
}

// RequireAdmin is HTTP middleware that 401s when the cookie is missing
// or invalid. Used on the admin handler group only.
func (a *Auth) RequireAdmin(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if _, err := a.verify(r); err != nil {
			writeError(w, http.StatusUnauthorized, "admin auth required")
			return
		}
		next.ServeHTTP(w, r)
	})
}

type claims struct {
	Role     string `json:"role"`
	IssuedAt int64  `json:"iat"`
}

func (a *Auth) signClaims(c claims) string {
	body, _ := json.Marshal(c)
	enc := base64.RawURLEncoding.EncodeToString(body)
	h := hmac.New(sha256.New, a.key)
	h.Write([]byte(enc))
	sig := base64.RawURLEncoding.EncodeToString(h.Sum(nil))
	return enc + "." + sig
}

func (a *Auth) verify(r *http.Request) (claims, error) {
	ck, err := r.Cookie(adminCookieName)
	if err != nil {
		return claims{}, err
	}
	parts := strings.SplitN(ck.Value, ".", 2)
	if len(parts) != 2 {
		return claims{}, errors.New("malformed cookie")
	}
	h := hmac.New(sha256.New, a.key)
	h.Write([]byte(parts[0]))
	expected := base64.RawURLEncoding.EncodeToString(h.Sum(nil))
	if !hmac.Equal([]byte(expected), []byte(parts[1])) {
		return claims{}, errors.New("bad signature")
	}
	body, err := base64.RawURLEncoding.DecodeString(parts[0])
	if err != nil {
		return claims{}, err
	}
	var c claims
	if err := json.Unmarshal(body, &c); err != nil {
		return claims{}, err
	}
	if c.Role == "" {
		return claims{}, errors.New("missing role")
	}
	return c, nil
}

// subtleEq is a constant-time string compare; returns nil on match.
func subtleEq(a, b string) error {
	if hmac.Equal([]byte(a), []byte(b)) {
		return nil
	}
	return errors.New("mismatch")
}

func writeJSON(w http.ResponseWriter, code int, v any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(code)
	_ = json.NewEncoder(w).Encode(v)
}

func writeError(w http.ResponseWriter, code int, msg string) {
	writeJSON(w, code, map[string]string{"error": msg})
}
